<?php

namespace Tests\Unit\Repositories;

use PHPUnit\Framework\TestCase;
use \App\Repositories\Users as UsersEntity;

class UsersTest extends TestCase
{

    /**
     * @var UsersEntity
     */
    private $repo;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app()->make(UsersEntity::class);
    }


    public function test_create()
    {
        $appendData = [
            'name' => 'Hello',
            'email' => 'omg@gmail.com',
            'password' => '66666',
            'nickname' => 'Cookie King'
        ];

        $primaryKey = $this->repo->append($appendData);

        $res = $this->repo->getDataByPrimaryKey($primaryKey);

        $afterData = $res->only(array_keys($appendData))->toArray();


        $this->assertEquals($afterData, $appendData);
    }
}
