language: php

php:
  - 7.2
  - 7.3
  - hhvm
services:
  - mysql

sudo: false

env:
  - APP_DEBUG=false
  - DB_PASSWORD=password
before_install:
  # Prepare MySQL schema
  - mysql -e "SET PASSWORD = PASSWORD('password');"
  - mysql -e 'CREATE DATABASE laravel;'

install:
  - composer install --prefer-dist --quiet
  -

script: phpunit -c phpunit.xml --coverage-text
