language: php

php:
  - 7.2
  - 7.3
  - hhvm
services:
  - mysql

sudo: false

env:
  - APP_DEBUG=false
  - DB_PASSWORD=password


before_install:
  # Prepare MySQL schema
  - mysql -e 'CREATE DATABASE laravel;'
  - mysql -e "SET PASSWORD = PASSWORD('password');"


install:
  - cp .env.example .env.testing
  - composer install --prefer-dist --quiet
  - php artisan migrate --env=testing

script: phpunit -c phpunit.xml --coverage-text
