<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use Tests\CreatesApplication;

class ExampleTest extends TestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        $this->createApplication();
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $this->assertTrue(true);
    }
}
